/* KCC-Q1-ALGN-5*/

INSERT INTO CMS_ADM_CMMI_CKC_PRD.QA_TEMP_TEST_CASE_SMRY
(TEST_CYC_SQNC_NUM, 
	PERIOD, RUN_ID, TEST_CASE_ID, AGGTN_GRP, AGGTN_SUB_GRP, 
	TESTED_REC_CNT, VLDTD_REC_CNT, FAILD_REC_CNT, RSLT_TXT, 
	TEST_CASE_STUS, EXCTN_TS, TEST_CASE_IND, DATA_TRND_IND, USER_NAME)


SELECT
	9999,
	TESTED.BLD_ID AS PERIOD,
	TRIM(TESTED.BLD_RUN_SK (FORMAT 'ZZZZZZZZZZZZZZZZZZZ9')) AS RUN_ID,
	'IDDOC-BL-1.10' AS TEST_CASE_ID,
	NULL AS AGGTN_GRP,
	NULL AS AGGTN_SUB_GRP,
	TESTED.TESTED_COUNT AS TESTED_REC_CNT,
	(TESTED.TESTED_COUNT - VALIDATED.VALIDATED_COUNT) AS VLDTD_REC_CNT,
	VALIDATED.VALIDATED_COUNT AS FAILD_REC_CNT,
	NULL AS RSLT_TXT,
	CASE WHEN TESTED_REC_CNT = VLDTD_REC_CNT THEN 'PASS' ELSE 'FAIL' END AS TEST_CASE_STUS,
	CURRENT_TIMESTAMP(0) AS EXCTN_TS,
	'Y' AS TEST_CASE_IND,
	'N' AS DATA_TRND_IND,
	USER AS USER_NAME
FROM
(
SELECT CLM_THRU_DT, COUNT(*) 
FROM CMS_ADM_CMMI_CKC_PRD.KCC_CKD_CLMS_HSTRY_IPQ2_PRD ALGN
INNER JOIN 
(
SELECT * FROM CMS_ADM_CMMI_CKC_PRD.KCC_ALGN_RUN_LOG_PY1_PRD
		WHERE ALGN_BLD_RUN_SK=20201112103427
) BLM_PRM

ON ALGN.BLD_RUN_SK = BLM_PRM.LTST_ALGN_BLD_RUN_SK
GROUP BY CLM_THRU_DT
) TESTED

CROSS JOIN
(
	(SELECT CLM_THRU_DT, COUNT(*) 
	FROM CMS_ADM_CMMI_CKC_PRD.KCC_CKD_CLMS_HSTRY_IPQ2_PRD ALGN
	INNER JOIN 	
	(
		SELECT * FROM CMS_ADM_CMMI_CKC_PRD.KCC_ALGN_RUN_LOG_PY1_PRD
		WHERE ALGN_BLD_RUN_SK=20201112103427
	) BLM_PRM
ON ALGN.BLD_RUN_SK = BLM_PRM.LTST_ALGN_BLD_RUN_SK
WHERE ALGN.CLM_THRU_DT < BLM_PRM.LKBCK_STRT_DT OR ALGN.CLM_THRU_DT > BLM_PRM.LKBCK_END_DT 
GROUP BY CLM_THRU_DT
		) B
) VALIDATED
;
