/* KCC-ALGN-151*/
/* PASS is zero rows returned */
/* CKD */
SELECT ALGN_QTR, COUNT(DISTINCT BENE_SK)
FROM CMS_ADM_CMMI_CKC_PRD.KCC_ALGN_DTLS_HSTRY_IPQ2_PRD 
WHERE BENE_SK in
    (SELECT DISTINCT BENE_SK
    FROM CMS_ADM_CMMI_CKC_PRD.KCC_ALGN_DTLS_HSTRY_IPQ2_PRD 
    WHERE BLD_RUN_SK=20201103104930
    AND ALGN_QTR = (
            SELECT BLD_ID 
            FROM CMS_ADM_CMMI_CKC_PRD.KCC_BLD_PRM_IPQ2_PRD 
            WHERE LTST_ALGN_BLD_RUN_SK = 20201103104930)
    AND PROS_BENE_DSGNTN_CD='CKD')
AND ALGN_QTR='IPQ1'
GROUP BY 1
