/* KCC-Q1-ALGN-12*/

/* 0 records returned is a pass condition*/

SELECT COUNT(DISTINCT (ALGN.BENE_SK))
--, ALGN.PROS_BENE_DSGNTN_CD,  BLM_PRM.BLD_ID, 
--CLM.CLM_TYPE_CD, CLM.CLM_THRU_DT
--, COUNT(*)

FROM  CMS_ADM_CMMI_CKC_PRD.KCC_ALGN_DTLS_HSTRY_IPQ2_PRD ALGN 
INNER JOIN 
(
    SELECT *
    FROM CMS_ADM_CMMI_CKC_PRD.KCC_BLD_PRM_IPQ2_PRD
    WHERE BLD_ID = 'IPQ2' 
	AND LTST_ALGN_BLD_RUN_SK = '20201103104930' 
	AND ALGN_RUN_IND = 'PRE'
) BLM_PRM
	ON   ALGN.BLD_ID = BLM_PRM.BLD_ID

INNER JOIN CMS_VDM_VIEW_MDCR_PRD.V2_MDCR_CLM AS CLM
	ON ALGN.BENE_SK = CLM.BENE_SK

--INNER JOIN CMS_VDM_VIEW_MDCR_PRD.V2_MDCR_CLM_LINE AS CLM_LN
	--ON    CLM.GEO_BENE_SK = CKD.GEO_BENE_SK 
	--AND CLM.CLM_DT_SGNTR_SK = CKD.CLM_DT_SGNTR_SK 
	--AND CLM.CLM_TYPE_CD = CKD.CLM_TYPE_CD 
	--AND CLM.CLM_NUM_SK = CKD.CLM_NUM_SK
LEFT OUTER JOIN CMS_VDM_VIEW_MDCR_PRD.V2_MDCR_CLM_RLT_COND_SGNTR_MBR COND    
   ON COND.CLM_RLT_COND_SGNTR_SK = CLM.CLM_RLT_COND_SGNTR_SK    

WHERE ALGN.PROS_BENE_DSGNTN_CD = 'CKD'
	-- AND CLM.CLM_TYPE_CD = 40
	AND COND.CLM_RLT_COND_SGNTR_SK = '84' --AKI
	AND CLM_BILL_FAC_TYPE_CD = '7'
	AND CLM_BILL_CLSFCTN_CD  = '2'
	AND CLM.CLM_ADJSTMT_TYPE_CD IN ('0', ' 0', '2', ' 2') 
	AND CLM.CLM_THRU_DT BETWEEN BLM_PRM.LKBCK_STRT_DT 
	AND BLM_PRM.LKBCK_END_DT   /* Prelimilary Alignment Claim Service Date filter */
	AND CLM.CLM_IDR_LD_DT BETWEEN BLM_PRM.LD_STRT_DT 
	AND BLM_PRM.LD_END_DT    /* Claim Load Date filter */
	--AND CLM.CLM_TYPE_CD in (10,82)

/* getting final verison using 'AS WAS' identification process */  
AND CLM.CLM_EFCTV_DT <= BLM_PRM.RUN_DT
AND CLM.CLM_OBSLT_DT  > BLM_PRM.RUN_DT
AND CLM_IDR_LD_DT <= BLM_PRM.RUN_DT
AND CLM.CLM_ERR_SGNTR_SK <> 3;
